language: node_js
node_js:
- '10'
cache: yarn
notifications:
  email: false
  slack:
    secure: 03FH96Bptu13boklbNf8LGuQ9jmupLeR1dlsWEPDcedzdwZGnA37IvEc24o5cyTlF4dqb4BRpjn7syq63FqCo6W68e8IULEDjGgl1x+M85sAHTabatE2YHB8wZEodaCyPR/zPbEZWP14hummGABASRC1tv68RngvaCQ87iQTbN6JeRhqZLx1RE1jUDRhuOyhLxlVTLwYJ3ZDQQxJCW4Lzy3XPKvB8p7XQ34ywIjy+4fTv2PWiSAnyvp5zrmq4kkyZxQzQBWosY8J0m0OyW9F9rCuZvjnXKs7OkGF+jZsvqwEqC36sTD/F5Aaw0S4vLuRdFZIvzdurNTNYX9QLgDhZdGu5OtpFOoiLgRNxdc8a7gc3c7ZXRtn+AzW5PVM3dqM18ArSgHfInDaO4bevrjxhhXLZFO4sUke67NLX/yEmUWn5//C4/m4Y9QHRvDYQPcnRP/c6EJWqdmRmfEmjictEjTrAuidTtUfjAcgFHx4FLHSEeVunfCWMIOWOPXmaK8sTKoAf9AZffeuyjh2UnXcaluIR5rCv/dlQqj2U+TOxfkkEF9J6UDqPyQUhJ25+2LVFi6HgmAoCLHb+DVJx4nJKRehGbDawZQp9rS+zSlYcQHMN4drhfJZDyAGHkYpIO8u/nMeAkXhnrSxvF0vwf9YrWgOwzmxkwcFKCcbV63mD1k=
