language: node_js
node_js:
  - '10'
cache: yarn
notifications:
  slack:
    secure: HtYj/bVhTvw88F/WbtPSRWx+0VxEt2zMns4T/mOWep5wsorYmn926+JFRYmmBJGZyCG2TXnobGMr4oONteaj7M8yY5Gvt93TgBXAb3D3I7eqYrWjomF04gv4lTUyKIfCPX7tGOOgNY47qO6KPUA/et1Hj+DU41O4Bw50yP9H0I420knc3Qo2jX6Q8dESMNTbaCSvS+EXQq1hLm4KtdLz3xXUUFqejVxUmRVoqpVnEgrbHOUPbAg97O4Bj1YwAogMkufNE9emQnfDEIh48BeA/THwCtbUTUA7IScPYfowbm5AyNMs1Z9gzu9wnhyxhlEQPMFgayzVzkHk+ZQLcBQIpa94f+oDIL1m3cP+h3V8s2JnDnr/Y6DH+qrlEJpJYN4TnSkXe9oRZPgB8XRWZNk7JNdIBVFOR3mEgSdZV74U3LhdO2/0LHUkxDKQEZBYGsJZwDiToeNOdRFN++TO/vdbXNLKe2lCDT7swls4mQekT3BlJuW5IMc4EurIMIqwaLVgM+UVubFfcIp+0kKtMGsi+x+KCP2a86w1+UdTyrofxJHmt4Kl5g1DTGR3MSXCtZtp08NKsZs+QQnkyiDmm/z6qUhxL1i69T3xNmus9c3FKbuLRU3s0bgabNyGinz5qgpGTKCFukzcz4nshfWoTqurjU0sR0li+RnOVyYBJvPWJeU=