language: node_js
node_js:
- '10'
notifications:
  slack:
    secure: DrXuB/kSJzo/ddA5+T8/yFhJg6SnOpm8nZp3X0jIbLoYh+Uhj1xJIjelNii9oI+4vWFwDMF63x4V0wDXCIKppfwrXg1FBy4TxrGJoOejOHDIKT05hTswsWAei1F6zNsYzIYlJ4DokLu8pZQtMWtKgM4zRiugTmn9HixxkW8QyQ84JhiZhpFHsm2PcwRJQCusHtGpBz1T64/NQA/lR1bq/I8BllgE3EeO5VGQO1Ga2Sdlri6G9qvUOgEivJGtzi5tSQZbWSuS+74O+MXZcP7lMXclU2ztlpSY+/GkEKG5ycjnVuSKQk+mIAihKUTGmZj1csRKaTwUj3rOLDkMztMbyHleTn7L5lZy6/wPvmNUtQlSGVCxxJZ6hEhCdltE1h6vo5uWuZeBuBH/kxZ0UkP1shrfOTASxZS5mOZ8pMuamrdXuU/5P8sIfofb0kl5GD1aFTLJW8JgSgOoyxGsaV4fL8OQE+2cqHlBcxxY8TqmcsX9S9wxKPBWE6FiKDvWlU/ewjx5UOtMcvJu8/MbVOG07RI1ogFDhVLJ5Jkl3quHJ9JcfGlRaQlQgkzdPBC1KHThFUFvX17FgPWHgWTvJXjMG/NAlNgH1UMxWNZBXtfUtBaDXP6DU9FyC5LifSbrl/j7KyYgKAwsqaOZN8X6LrLx5YzFQp95gmv60rciMfGIt4Q=
