language: node_js
node_js:
- '10'
cache: yarn
notifications:
  email: false
  slack:
    secure: wzdg1a7H9wjZlIJ5QDWdkZYVWNCNeb04TXn/SKprm/CkmbqkkprRZaxjdSOhkP/WIAPu/N5Mrsaj2ejitiX8ewkGsVmKyNPOHQe3B+KyuK1dpVRDXsqydVOP/pk5DEvNJ2xCNJv68ppH4ipXmnnNA0vic/jnFjPy+G4aKmkdAUS0TUcHWR/+eYItR3xkQH/CtEdzDjl1xgA/ATlQNax8OmDkBSdbiSClJvNuHaro+EdwP8TZgaPjWCqxgSKTURgNTjgXLZUPekJ99eO4n3AUO9vKkNAuMbrjm9fVWDmbzDmk6CTocs5RV0gD6yymiPlFFQ5BQW6RvEw5nwbb7AzppqKSjPRYgKxsqhjk8Cygq0PpwdEsf2NB4FsLrvSkryoFe5oD3EC4RIitt3DV4N0Zhr3h9V0u6rwFBfIVy90Sx77Gh6X6npWq+ssuUrGikIAu+mwAHmfMVimV3cYKI681c0/k8lLe+3JP6ixxthi+SVgi+xSUDA8nhuWSQmHYnaWJcDv+Y1qBF2hr18eaphqQXn1L6uiQG8v/MoWhXynR9NpthW6gphWo9JIannqRpLQYR9HNWXXlXmftfw6OOQ6+D0bcY04MjIp+RIXF7cxs1u7i7nEHMJUJSzsRpwZdJBMBVzHJ80mmH+G8IFNT8XjVtuMq0RvU8HJl9nYKzPRnm74=
